### ISSUE TITLE
ELB plugin - difference between   dimensions_name & dimensions_value 

### ISSUE THREAD

**Issue by ctippur** [yunomu/fluent-plugin-cloudwatch#19]
Hello,

I am trying to use this plugin to get alerts from CW. 

I seem to get UnHealthyHostCount datapoints is empty even after generating an alert.

Can you please clarify the difference between them? Maybe I have it setup wrongly.
  
dimensions_name LoadBalancerName
  dimensions_value YOUR_ELB_NAME

- Shekar

**Comment by fujiwara** [comment]
Can you paste your configuration (except aws_key_id and aws_sec_key)?
I got UnHealthyHostCount value by this configuration.

```
<source>
  type cloudwatch
  tag  cloudwatch.elb_health
  aws_key_id  xxxx
  aws_sec_key xxxx
  cw_endpoint monitoring.ap-northeast-1.amazonaws.com
  namespace AWS/ELB
  metric_name HealthyHostCount,UnHealthyHostCount
  dimensions_name LoadBalancerName
  dimensions_value my-elb-name
  statistics Average
</source>
```

http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/US_MonitoringLoadBalancerWithCW.html
> UnHealthyHostCount
> The count of the number of unhealthy instances in each Availability Zone. Hosts that have failed more health checks than the value of the unhealthy threshold are considered unhealthy. If cross-zone is enabled, the count of the number of unhealthy instances is calculated for all Availability Zones. Instances may become unhealthy due to connectivity issues, health checks returning non-200 responses (in the case of HTTP or HTTPS health checks), or timeouts when performing the health check.
>
> Preferred statistic: average

If your ELB is cross-zone enabled and `statistics Minimum`, reported value will be minimum  UnHealthyHostCount for each zones.

**Comment by ctippur** [comment]
This is what I have. I still see


2015-02-26 10:11:27 -0800 [warn]: cloudwatch: AWS/ELB LoadBalancerName
fps-preprod UnHealthyHostCount datapoints is empty


<source>

  type cloudwatch

  tag  alert.cloudwatch.raw

  aws_key_id  XXX

  aws_sec_key XXX

  cw_endpoint monitoring.us-west-2.amazonaws.com

  interval 5

  namespace AWS/ELB

  metric_name
HealthyHostCount,HTTPCode_Backend_2XX,HTTPCode_Backend_3XX,HTTPCode_Backend_4XX,HTTPCode_Backend_5XX,HTTPCode_ELB_4XX,Latency,RequestCount,UnHealthyHostCount

  dimensions_name LoadBalancerName

  dimensions_value fps-preprod

</source>

**Comment by fujiwara** [comment]
hmm... other metrics was received collectly?

**Comment by ctippur** [comment]
I am unable to get any metric.

**Comment by ctippur** [comment]
I think we had a wrong region name. It is resolved now.
Thanks.
Shekar
