### ISSUE TITLE
hello sir plz help me 21-2017

### ISSUE THREAD

**Issue by chansanto** [yunomu/fluent-plugin-cloudwatch#33]
I config 
```
<source>
  @type cloudwatch
  tag  cloudwatch
  aws_key_id XXXXX
  aws_sec_key XXXXXX
  cw_endpoint 54.251.142.201(fluent server)
  region ap-southeast-1
  namespace AWS/EC2
  metric_name CPUUtilization
  dimensions_name InstanceId
  dimensions_value i-XXXXXXX
  interval 10
</source><match cloudwatch>
  @type copy
   <store>
    @type file
    path /tmp/cloudwatch123
  </store>
</match>
```

and it failed :(. it's said error log : 2017-06-21 12:25:14 +0900 [warn]: #0 cloudwatch: watcher thread is not working after 2017-06-21 12:24:54 +0900. Restarting...

**Comment by fujiwara** [comment]
Hi.

>   cw_endpoint 54.251.142.201(fluent server)

It seems wrong. `cw_endpoint` is must be AWS cloudwatch endpoint for your region.
http://docs.aws.amazon.com/general/latest/gr/rande.html#cw_region
Please check it.

**Comment by chansanto** [comment]
thanks sir 
:+1: you saved me, 
```
# tail /var/log/td-agent/td-agent.log
2017-06-21 14:22:00.000000000 +0900 cloudwatch: {"CPUUtilization":0.068}
```

can you help me about
 <match cloudwatch>
  @type copy
   <store>
    @type file
    path /tmp/cloudwatch123
  </store>
</match>
 :( i dont see any files in /tmp/cloudwatch123

**Comment by chansanto** [comment]
it's okie now :) thanks a lot .
